### ISSUE TITLE
Löschen

### ISSUE THREAD

**Issue by esze94** [xDivisionByZerox/find-duplicate-images#7]
Hallo! Wäre das möglich, dass du die Fotos sofort löschbar machst? Einzelne bzw. alle doppelte Fotos mit einem Klick zu löschen?

**Comment by xDivisionByZerox** [comment]
Ist an sich geplant. Ich nehme das als Feature auf. Mal sehen wann sich das umsetzen lässt.

**Comment by xDivisionByZerox** [comment]
Feature wurde mit #12 hinzugefügt. Schau dir die neue Projektbeschreibung an um mehr Infos zu erhalten.
